name: Update BM approvers

on:
  push:
    branches: [ "main" ]

permissions: write-all
  #issues: write

jobs:     
  update-approvers:
    name: update-approvers
    runs-on: ubuntu-latest
#     permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Get UserIDs
        run: |
          ls -la
          array=($(jq '.[].reviewers[].id' .github/workflows/envRules.json))
          JSON_STRING='{"reviewers":['
          for userId in ${array[@]}; do 
            JSON_STRING=$JSON_STRING'{"type":"User","id":'"$userId"'},'
          done
          JSON_STRING=$JSON_STRING']}'
          # Get the position of the last comma
          last_comma=$(echo "$JSON_STRING" | grep -aob ',' | tail -1 | cut -d':' -f1)
          # Remove the last comma from the string
          JSON_STRING=${JSON_STRING:0:last_comma}${JSON_STRING:last_comma+1}
          echo "JSON_STRING=$JSON_STRING" >> $GITHUB_ENV

        
      - name: Update environment settings for repos
        run: |
            echo $JSON_STRING
            REPOS=()
            exec 3< ".github/workflows/includedRepos.txt"

            # Read the file line by line
            while IFS= read -r line <&3 || [ -n "$line" ]; do
              # Process each line (you can replace this with your own logic)
              echo "Processing line: $line"
            done

            # Close the file descriptor
            exec 3<&-
